### ISSUE TITLE
rewrite in .NET MAUI

### ISSUE THREAD

**Issue by win4r** [microsoft/chat-copilot#217] opened 2023-08-19 03:01 UTC
rewrite in .NET MAUI

**Comment by crickman** [comment] 2023-08-20 17:19
[Maui](https://learn.microsoft.com/en-us/dotnet/maui/what-is-maui)

Thanks for the suggestion! We're looking into blazer/maui for app and sample front-ends moving forward, and we're always open to contributions from the community.

Duplicate of https://github.com/microsoft/chat-copilot/issues/197
Duplicate of https://github.com/microsoft/chat-copilot/issues/210

**Closed by crickman** 2023-08-20 17:19 UTC
Labels: duplicate, enhancement, webapp, webapi, external issue
