### ISSUE TITLE
WebSearcher plugin not working

### ISSUE THREAD

**Issue by yanxiaodi** [microsoft/chat-copilot#549] opened 2023-10-28 11:36 UTC
**Describe the bug**

I deployed the web searcher plugin but when I enable it, it returns 500 errors.
![image](https://github.com/microsoft/chat-copilot/assets/3395915/26df5d15-1b8d-4e3f-a00f-b88b5f83c8fc)

The bing seach service is deployed correctly. And the api key of Bing search is also correct in the web searcher plugin.
![image](https://github.com/microsoft/chat-copilot/assets/3395915/40459da5-26b2-49fd-a203-f57981201b36)

Update:
I tried to run the app locally. When I enabled the web searcher plugin, it prompted me to input a key:
![image](https://github.com/microsoft/chat-copilot/assets/3395915/ec5060f2-9785-4fc0-8282-f7a171c44165)

I didn't see this in Azure apps:
![image](https://github.com/microsoft/chat-copilot/assets/3395915/f7535ce9-a630-43be-8e03-e04c1009fc21)

I guess it's because the chat app cannot access the web searcher function without the key？

Another potential issue is that the planner doesn't work. I can see the planner requests in local app but cannot see that in the Azure app.

**To Reproduce**
1. Deploy all the resources
2. Deploy the web searcher using the `deploy-plugins.ps1` script.
3. Enable the web searcher plugin for the chat session.
4. Send a message, and see the error.

**Expected behavior**
The web searcher plugin should work. 

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by blin455** [comment] 2023-10-28 23:38
I'm also experiencing same issue, I realized in the webapi webapp configuration, there is a field called Plugin:1:Key, are we supposed to replace this with Web Search PAT? 
![image](https://github.com/microsoft/chat-copilot/assets/143014109/a318a84b-4407-401d-a6a5-2ed29f993bb3)

In addition to that, the Klarna plugin was also not working. The planner was invoked but return 404.
![image](https://github.com/microsoft/chat-copilot/assets/143014109/af97f26b-5cf2-4f97-b7ab-4683ae6e27b1)

**Comment by yanxiaodi** [comment] 2023-10-29 00:22
@blin455 I got the same error as below:
![image](https://github.com/microsoft/chat-copilot/assets/3395915/a95bd2ad-81c0-4501-8307-156a87a223cb)
It seems the planner can make the plan, but the plugin doesn't work.

**Comment by crickman** [comment] 2023-10-30 16:47
Thank you for this feedback and clear-data points.

**Comment by kenny-tao** [comment] 2023-10-31 13:31
> Thank you for this feedback and clear-data points.

Seems the issue with Klarna plug-in is the incorrect server_url in the generated plan. It uses https://www.klarna.com/ instead of https://www.klarna.com/us/shopping specified in the metadata.

<img width="440" alt="image" src="https://github.com/microsoft/chat-copilot/assets/28410272/ffa8abf5-530e-4a13-b729-cd48ab03edd4">
<img width="458" alt="image" src="https://github.com/microsoft/chat-copilot/assets/28410272/eede811b-10b2-4893-b866-c884fc94595d">

**Comment by kenny-tao** [comment] 2023-10-31 13:53
> Just to add on, I changed the Planner Type to "Stepwise" instead of "Sequential" in appsettings.json under webapi folder. The Klarna plugin works. ![image](https://user-images.githubusercontent.com/143014109/279144175-ee037e9b-d0e4-484d-8f26-069f44523c24.png)

Thanks for sharing. It works using Stepwise planner. but it gives answer straight away without showing the plan, and there is nothing logged under Plans page as well. Seems a missing feature.

**Comment by crickman** [comment] 2023-11-08 15:53
@kenny-tao - There is a currently known issue with Klarna, I suspect this isn't related to the posted issue.

**Comment by crickman** [comment] 2023-11-08 15:55
@yanxiaodi - when configuring websearch plugin client-side you need to provide the API key.  When configuring as a hosted-plugin, this key must be defined as part of the api configuration/environment.

Can you please confirm you have an API key and have provided it to the plug-in?

Can you also please share which version of semantic-kernel you have referenced (there have been some updates around function calling that may be in-play.)

**Comment by yanxiaodi** [comment] 2023-11-09 08:34
Thanks @crickman , I'll try the latest version this weekend.

**Comment by NicolasHumann** [comment] 2023-11-11 21:01
Hi,
The problem is {functions url}/swagger.json return a 404.
There is no swagger generation in the plugin code.

**Comment by yanxiaodi** [comment] 2023-11-12 03:26
Hi @crickman , I have configured the Bing api key as shown below:
![image](https://github.com/microsoft/chat-copilot/assets/3395915/8a8fe6c5-23a6-48e8-a5ef-6a2fae3da83d)

**Comment by crickman** [comment] 2023-11-16 17:23
If you've configured the plugin as "hosted", then you won't be prompted for the key.  Please double check your key configuration (perhaps with a debugger and breakpoint?)

I'll reverify functionality with the current repo state today.

**Comment by yanxiaodi** [comment] 2023-11-17 06:52
@crickman  The weird thing is that when I run the app locally, the web search plugin works. Could you please show me what key configuration I need to check? I've checked the Bing api key which is correct.

**Comment by crickman** [comment] 2023-11-27 18:16
Here is what we are depoying (key obscured):

<img width="603" alt="image" src="https://github.com/microsoft/chat-copilot/assets/66376200/60bce1fb-1d9c-46dd-a6f3-82b1fee1f365">

> Note: this is the second plug-in, klarna is the first (index 0)

I'm still seeing issue with our INT deployment as well, even after all the dust has landed with the SK updates and what-not.

Going to walk through this end-to-end today and sync up with @momuno

**Comment by evchaki** [comment] 2024-03-20 21:10
It looks like this is now working with the 1.0 kernel.
![image](https://github.com/microsoft/chat-copilot/assets/37411713/415d3528-5203-4b54-a2d4-5b075b49549f)

**Closed by evchaki** 2024-03-20 21:11 UTC
Labels: bug, webapi, PR: regression fix
