### ISSUE TITLE
AIException reference missing in dotnet - doesn't compile with main version of semantic kernel

### ISSUE THREAD

**Issue by benm5678** [microsoft/chat-copilot#318] opened 2023-09-09 20:29 UTC
I'm trying to compile the app with my own branch of semantic kernel I forked from main and it fails since can't find this AIException class.  Searching codebase cannot find it defined in dotnet code, only in python.  Even when searching release branch of exact version copilot uses from nuget I can't find it (0.21.230828.2-preview).  Any ideas how to get it working?

> chat-copilot/webapi/Controllers/ChatController.cs(158,41): error CS0246: The type or namespace name 'AIException' could not be found (are you missing a using directive or an assembly reference?)

**Comment by alliscode** [comment] 2023-09-11 16:27
Hi @benm5678, thanks for filing this issue. It looks like `AIException` was recently removed from the Microsoft.SemanticKernel.Abstractions package in [this release](https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-0.22.230905.3-preview),  [see this PR](https://github.com/microsoft/semantic-kernel/commit/7e7c4b8ab01e1e0efd5193797661e9813208399e). Chat-copilot is currently using a [slightly older of release](https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-0.21.230828.2-preview) and this is why you are seeing a mismatch.

We will update copilot-chat to the latest SK release early this week and we'll let you know when it's done.

**Comment by alliscode** [comment] 2023-09-11 18:12
@benm5678 we have updated the SK packages to `0.23.230906.2-preview`. If you pull the latest from main it should resolve your issue. I'm closing this issue for now but please reopen it if you feel the issue is not resolved. Thanks!

**Closed by alliscode** 2023-09-11 18:12 UTC
