### ISSUE TITLE
Deployment template not working with bing-search failure

### ISSUE THREAD

**Issue by yanxiaodi** [microsoft/chat-copilot#498] opened 2023-10-13 09:50 UTC
**Describe the bug**

I tried two ways to deploy the app but got similar errors.

* Manual deployment: I got a warning `Warning BCP081: Resource type "Microsoft.Bing/accounts@2020-06-10" does not have types available.`. The script run a long time then failed.
* Using the deployment template: One deployment task failed: `function-copichat-7tz57cfyqmyry-websearcher-plugin/default`. 

I suspect it's related to the bing-search component. Not sure if it's the same problem as this issue: #491 

Thanks.

**To Reproduce**
1. Go to `https://github.com/microsoft/chat-copilot/blob/main/scripts/deploy/README.md`
2. Click on **Deploy to Azure**
3. Fill the fields and deploy

**Expected behavior**
The deployment should complete without errors.

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/3395915/fe9c0c5c-515f-4900-aa63-dfb59cbf849c)
![image](https://github.com/microsoft/chat-copilot/assets/3395915/7c5fe337-f89c-4147-8831-9da1f1dbb7d8)

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by threegitty350** [comment] 2023-10-13 14:53
Same issue as I'm experiencing. "Warning BCP081: Resource type "Microsoft.Bing/accounts@2020-06-10" does not have types available." is also what I get

**Comment by yanxiaodi** [comment] 2023-10-13 20:50
@TaoChenOSU Thanks. The version is `Bicep CLI version 0.22.6 (d62b94db31)`

**Comment by yanxiaodi** [comment] 2023-10-14 05:43
I guess Bicep doesn't support Bing search? I saw a warning as follows:
![image](https://github.com/microsoft/chat-copilot/assets/3395915/c4d56c75-1407-496e-8b6d-095f16cbd607)

**Comment by threegitty350** [comment] 2023-10-16 15:19
Adding to this:

Bicep CLI version 0.21.1  > upgraded to > Bicep CLI v0.22.6 Did not result in a different outcome

**Warning BCP081: Resource type "Microsoft.Bing/accounts@2020-06-10" does not have types available.**

`{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/[REDACTED]/resourceGroups/rg-[REDACTED]/providers/Microsoft.Resources/deployments/[REDACTED]","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","target":"/subscriptions/[REDACTED]/resourceGroups/rg-[REDACTED]/providers/Microsoft.Resources/deployments/[REDACTED]","message":"{\r\n  \"Code\": \"BadRequest\",\r\n  \"Message\": \"Encountered an error (ServiceUnavailable) from host runtime.\",\r\n  \"Target\": null,\r\n  \"Details\": [\r\n    {\r\n      \"Message\": \"Encountered an error (ServiceUnavailable) from host runtime.\"\r\n    },\r\n    {\r\n      \"Code\": \"BadRequest\"\r\n    },\r\n    {\r\n      \"ErrorEntity\": {\r\n        \"Code\": \"BadRequest\",\r\n        \"Message\": \"Encountered an error (ServiceUnavailable) from host runtime.\"\r\n      }\r\n    }\r\n  ],\r\n  \"Innererror\": null\r\n}"}]}}`

**Comment by TaoChenOSU** [comment] 2023-10-16 16:57
This is likely due to a race condition in getting the function host key @glahaye

**Comment by glahaye** [comment] 2023-10-16 23:40
Or a race condition caused by a clash of App Insights resources and config of the Bing Search Plugin Host.

I have a potential fix if my theory is correct.  Testing it right now.

**Comment by TaoChenOSU** [comment] 2023-10-17 21:13
The Web Searcher plugin has become optional (default to NOT deploy) when you deploy using the deploy-azure scripts. PR: https://github.com/microsoft/chat-copilot/pull/517. 

Closing as the PR will address this issue. Feel free to reopen if you have further questions.

**Closed by TaoChenOSU** 2023-10-17 21:13 UTC
Labels: deployment

**Comment by yanxiaodi** [comment] 2023-10-19 06:18
Thanks @TaoChenOSU . But I got another error:

> {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/76760d52-2d57-4b56-9ba6-f0f5044f60a6/resourceGroups/rg-chat-copilot/providers/Microsoft.Resources/deployments/chat-copilot","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/76760d52-2d57-4b56-9ba6-f0f5044f60a6/resourceGroups/rg-chat-copilot/providers/Microsoft.Web/sites/app-copichat-7tz57cfyqmyry-memorypipeline/extensions/MSDeploy","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'failed'.","details":[{"code":"Failed","message":"Deployment was interrupted and the process running it was terminated unexpectedly, if an ARM template is used, the likely cause is a race condition. To solve the race condition, make all resources that could potentially restart the site (app settings or site config changes for example) have a dependency on MSDeploy resource. For more info please read the information here: http://go.microsoft.com/fwlink/?LinkId=808141"}]}]}}

Not sure if I need to create a new issue? Thanks.

**Comment by yanxiaodi** [comment] 2023-10-19 06:24
The failed one is `app-copichat-7tz57cfyqmyry-memorypipeline/MSDeploy`.

> ERROR TYPE
Deployment was interrupted and the process running it was terminated unexpectedly, if an ARM template is used, the likely cause is a race condition. To solve the race condition, make all resources that could potentially restart the site (app settings or site config changes for example) have a dependency on MSDeploy resource. For more info please read the information here: http://go.microsoft.com/fwlink/?LinkId=808141 (Code: Failed)

**Comment by glahaye** [comment] 2023-10-19 20:37
@yanxiaodi We are aware of this issue and hope to have a fix today.

In the meantime, you can work around the problem by simply deploying again (without deleting the resources of the failed deployment).
