### ISSUE TITLE
dependabot[bot] Bump Roslynator.Analyzers from 4.6.0 to 4.6.1 in /webapi (#553)

### ISSUE THREAD

**Issue by howard2019007** [microsoft/chat-copilot#565] opened 2023-11-02 05:15 UTC
**Describe the bug**

There is a problem with the deployment of the new version, and by default it stays at Looking for your backend without any action

**Comment by glahaye** [comment] 2023-11-02 18:28
Duplicate of #523 and #545

This is due to the backing storage running out of indexes.

Will add more information in #545 

Will also make error more obvious.

**Closed by glahaye** 2023-11-02 18:28 UTC
